changelog:
  exclude:
    labels:
      - github_actions
      - auto-release
      - ci
  categories:
    - title: Changes
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: Dependencies
      labels:
        - dependencies
