/**
 * Regenerates the two icon tables from the pinned `lucide-static` package:
 *
 *   renderer/icon-codepoints.ts — every glyph in font/lucide.woff2 (aliases
 *     included) → its codepoint. The renderer paints icons through it, so a
 *     stored name keeps rendering even if Lucide later renames the icon.
 *   src/icon-battery.ts — the canonical icons with their search tags, served
 *     to the config window's icon picker over IPC (`icons:get`).
 *
 * Both are derived data: run `pnpm generate:icons` after bumping
 * lucide-static. tests/generate-icons.test.ts fails while they are stale.
 * The font's own info.json is the source of truth for which glyphs exist —
 * codepoints.json still lists retired brand icons the font no longer draws.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { isEntrypoint } from './lib/script-runtime.ts';

type FontInfo = Readonly<Record<string, { encodedCode: string }>>;
type IconTags = Readonly<Record<string, readonly string[]>>;

export interface LucideMetadata {
  info: FontInfo;
  tags: IconTags;
  version: string;
}

export function readLucideMetadata(root: string): LucideMetadata {
  const pkg = path.join(root, 'node_modules', 'lucide-static');
  const readJson = (file: string): unknown =>
    JSON.parse(readFileSync(path.join(pkg, file), 'utf8'));
  const { version } = readJson('package.json') as { version: string };
  return {
    info: readJson('font/info.json') as FontInfo,
    tags: readJson('tags.json') as IconTags,
    version,
  };
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function codepointOf(name: string, encodedCode: string): number {
  const match = /^\\([0-9a-f]{4,5})$/i.exec(encodedCode);
  if (!match?.[1]) throw new Error(`Unparseable codepoint for ${name}`);
  return parseInt(match[1], 16);
}

export function buildIconModules(
  info: FontInfo,
  tags: IconTags,
  version: string,
): { codepoints: string; battery: string } {
  const names = Object.keys(info).sort();
  const header = (what: string): string =>
    `/**\n * ${what}\n *\n * GENERATED by scripts/generate-icons.ts from lucide-static@${version}\n` +
    ' * (ISC licence) — do not edit by hand; run `pnpm generate:icons`.\n */\n';

  const codepointLines = names.map(
    (name) =>
      `  ${quote(name)}: 0x${codepointOf(name, info[name]?.encodedCode ?? '').toString(16)},\n`,
  );
  const codepoints =
    header('Lucide icon name → codepoint in assets/fonts/lucide.woff2.') +
    'export const ICON_CODEPOINTS: Readonly<Record<string, number>> = {\n' +
    codepointLines.join('') +
    '};\n';

  const batteryLines = Object.keys(tags)
    .filter((name) => Object.hasOwn(info, name))
    .sort()
    .map(
      (name) =>
        `  { name: ${quote(name)}, tags: [${(tags[name] ?? []).map(quote).join(', ')}] },\n`,
    );
  const battery =
    header('Canonical Lucide icons and their search tags (icon picker).') +
    "import type { IconBatteryItem } from './ipc-contract.js';\n\n" +
    'export const ICON_BATTERY: readonly IconBatteryItem[] = [\n' +
    batteryLines.join('') +
    '];\n';
  return { codepoints, battery };
}

// Direct execution: node --experimental-strip-types scripts/generate-icons.ts
if (isEntrypoint(import.meta.url)) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const meta = readLucideMetadata(root);
  const { codepoints, battery } = buildIconModules(
    meta.info,
    meta.tags,
    meta.version,
  );
  writeFileSync(path.join(root, 'renderer', 'icon-codepoints.ts'), codepoints);
  writeFileSync(path.join(root, 'src', 'icon-battery.ts'), battery);
}
