/**
 * Spanish search terms for the vocabulary of the Lucide icon battery, so the
 * picker finds `shopping-cart` by «carrito» and `lock` by «candado».
 *
 * HAND-AUTHORED, not generated: a word-level dictionary from each English
 * word in icon names and tags to one or more Spanish terms, separated by
 * `|`. Every word of every icon NAME is either translated here or listed in
 * ICON_SEARCH_ES_UNTRANSLATED; tests/icon-search-es.test.ts enforces that,
 * so a Lucide bump that brings new words fails until they are handled. Tag
 * words are covered for the frequent ones. A flat data table, exempt from
 * max-lines in eslint.config.ts; src/icon-search.ts applies it.
 */
export const ICON_SEARCH_ES: Readonly<Record<string, string>> = {
  // ── Words in icon names ──
  accessibility: 'accesibilidad',
  activity: 'actividad',
  ad: 'anuncio|publicidad',
  air: 'aire',
  alarm: 'alarma',
  album: 'álbum',
  alert: 'alerta|aviso',
  align: 'alinear',
  all: 'todo|todos',
  alto: 'contralto',
  ambulance: 'ambulancia',
  ampersand: 'et|y',
  ampersands: 'et|y',
  amphora: 'ánfora',
  anchor: 'ancla',
  and: 'y',
  angle: 'ángulo',
  angry: 'enfadado|enojado',
  antenna: 'antena',
  anvil: 'yunque',
  aperture: 'apertura|diafragma',
  app: 'aplicación',
  apple: 'manzana',
  approximately: 'aproximadamente',
  aquarius: 'acuario',
  archive: 'archivo|archivar',
  area: 'área',
  arm: 'brazo',
  armchair: 'sillón|butaca',
  around: 'alrededor',
  arrow: 'flecha',
  arrows: 'flechas',
  ascending: 'ascendente',
  asterisk: 'asterisco',
  astroid: 'astroide',
  at: 'arroba',
  atom: 'átomo',
  award: 'premio|galardón',
  axe: 'hacha',
  axes: 'ejes',
  axis: 'eje',
  baby: 'bebé',
  back: 'atrás|volver',
  backpack: 'mochila',
  backup: 'copia de seguridad|respaldo',
  badge: 'insignia|distintivo',
  bag: 'bolsa',
  baggage: 'equipaje',
  balloon: 'globo',
  ban: 'prohibido|bloquear',
  banana: 'plátano',
  bandage: 'venda|tirita',
  bank: 'banco',
  banknote: 'billete',
  bar: 'barra',
  barcode: 'código de barras',
  barrel: 'barril',
  baseline: 'línea base',
  basket: 'cesta',
  bass: 'bajo',
  bath: 'bañera|baño',
  battery: 'batería|pila',
  beaker: 'vaso de precipitados',
  bean: 'judía|frijol|alubia',
  bed: 'cama',
  beef: 'ternera|carne',
  beer: 'cerveza',
  bell: 'campana|notificación',
  belt: 'cinturón',
  between: 'entre',
  biceps: 'bíceps',
  big: 'grande',
  bike: 'bicicleta|bici',
  binary: 'binario',
  binoculars: 'prismáticos|binoculares',
  biohazard: 'riesgo biológico',
  bird: 'pájaro|ave',
  birdhouse: 'pajarera|casita de pájaros',
  bishop: 'alfil|obispo',
  blend: 'mezclar|fusionar',
  blender: 'batidora|licuadora',
  blinds: 'persianas',
  blocks: 'bloques',
  board: 'tablero|pizarra',
  bold: 'negrita',
  bolt: 'tornillo|rayo',
  bomb: 'bomba',
  bone: 'hueso',
  book: 'libro',
  bookmark: 'marcador|favorito',
  boom: 'radiocasete|explosión',
  bot: 'robot',
  bottle: 'botella',
  bottom: 'abajo|inferior',
  bow: 'arco|lazo',
  bowl: 'cuenco|bol',
  box: 'caja',
  boxes: 'cajas',
  braces: 'llaves',
  brackets: 'corchetes',
  brain: 'cerebro',
  branch: 'rama',
  brick: 'ladrillo',
  bridge: 'puente',
  briefcase: 'maletín',
  bring: 'traer',
  broccoli: 'brócoli',
  broom: 'escoba',
  brush: 'pincel|cepillo',
  bubbles: 'burbujas',
  bucket: 'cubo|balde',
  bug: 'error|bicho|fallo',
  building: 'edificio',
  buoy: 'boya',
  bus: 'autobús',
  business: 'negocio|empresa',
  cake: 'tarta|pastel',
  calculator: 'calculadora',
  calendar: 'calendario',
  calendars: 'calendarios',
  call: 'llamada|llamar',
  camera: 'cámara',
  can: 'lata',
  cancer: 'cáncer',
  candlestick: 'velas|candelabro',
  candy: 'caramelo|golosina',
  cane: 'bastón',
  cannabis: 'marihuana',
  cap: 'gorra|tapón',
  capricorn: 'capricornio',
  caption: 'subtítulo|leyenda',
  captions: 'subtítulos',
  car: 'coche|automóvil',
  caravan: 'caravana',
  card: 'tarjeta',
  cards: 'tarjetas|cartas',
  cargo: 'carga',
  carrot: 'zanahoria',
  cart: 'carrito|carro',
  carton: 'cartón|brik',
  case: 'mayúsculas|minúsculas|funda',
  cassette: 'casete',
  cast: 'transmitir|emitir',
  castle: 'castillo',
  cat: 'gato',
  cctv: 'videovigilancia|cámara de seguridad',
  ccw: 'antihorario',
  ceiling: 'techo',
  cells: 'celdas',
  cent: 'céntimo|centavo',
  center: 'centro|centrar',
  centerline: 'línea central',
  chair: 'silla',
  charger: 'cargador',
  charging: 'cargando',
  chart: 'gráfico|gráfica',
  check: 'marca|comprobar|visto|correcto',
  checks: 'marcas|comprobaciones',
  chef: 'cocinero',
  cherry: 'cereza',
  chess: 'ajedrez',
  chevron: 'flecha|cheurón',
  chevrons: 'flechas',
  church: 'iglesia',
  cigarette: 'cigarrillo|tabaco',
  circle: 'círculo',
  circuit: 'circuito',
  citrus: 'cítrico|limón',
  claim: 'reclamar|reclamación',
  clapperboard: 'claqueta',
  cleaning: 'limpieza',
  clef: 'clave',
  click: 'clic|pulsar',
  clipboard: 'portapapeles',
  clock: 'reloj|hora',
  close: 'cerrar',
  closed: 'cerrado',
  cloud: 'nube',
  cloudy: 'nublado',
  clover: 'trébol',
  club: 'trébol',
  coaster: 'posavasos',
  code: 'código',
  coffee: 'café',
  cog: 'engranaje|ajustes',
  coins: 'monedas',
  collapse: 'contraer|plegar',
  column: 'columna',
  columns: 'columnas',
  combine: 'combinar',
  combined: 'combinado',
  command: 'comando',
  commit: 'confirmación',
  commons: 'comunes',
  compare: 'comparar',
  compass: 'brújula',
  complex: 'complejo',
  component: 'componente',
  computer: 'ordenador|computadora',
  concave: 'cóncavo',
  concierge: 'conserje|recepción',
  cone: 'cono',
  conflict: 'conflicto',
  conical: 'cónico',
  connected: 'conectado',
  construction: 'construcción|obras',
  contact: 'contacto',
  container: 'contenedor',
  contents: 'contenido',
  contrast: 'contraste',
  convex: 'convexo',
  conveyor: 'cinta transportadora',
  cookie: 'galleta',
  cooking: 'cocinar|cocina',
  copy: 'copiar',
  copyright: 'derechos de autor',
  corner: 'esquina',
  cpu: 'procesador',
  crack: 'grieta',
  crash: 'choque|fallo',
  cream: 'crema|nata',
  create: 'crear',
  creative: 'creativo',
  credit: 'crédito',
  croissant: 'cruasán',
  crop: 'recortar',
  cross: 'cruz',
  crossed: 'cruzado|tachado',
  crosshair: 'mira|punto de mira',
  crown: 'corona',
  cuboid: 'cuboide|ortoedro',
  cup: 'taza|copa',
  cupcake: 'magdalena',
  currency: 'moneda|divisa',
  cw: 'horario',
  cylinder: 'cilindro',
  dam: 'presa',
  dash: 'guion|raya',
  dashboard: 'panel|tablero',
  dashed: 'discontinuo',
  database: 'base de datos',
  days: 'días',
  deciduous: 'caducifolio|árbol',
  decimals: 'decimales',
  decrease: 'disminuir|reducir',
  decreasing: 'decreciente',
  delete: 'borrar|eliminar',
  descending: 'descendente',
  desk: 'escritorio',
  dessert: 'postre',
  diameter: 'diámetro',
  diamond: 'diamante|rombo',
  dice: 'dado|dados',
  dices: 'dados',
  diff: 'diferencias',
  digit: 'dígito',
  dim: 'atenuar|tenue',
  dimension: 'dimensión',
  dimensions: 'dimensiones',
  directional: 'direccional',
  disc: 'disco',
  dish: 'plato|antena parabólica',
  dispenser: 'dispensador',
  distribute: 'distribuir',
  divide: 'dividir',
  dna: 'adn',
  dock: 'base|muelle',
  dog: 'perro',
  dollar: 'dólar',
  dome: 'cúpula',
  donut: 'dónut|rosquilla',
  door: 'puerta',
  dot: 'punto',
  double: 'doble',
  down: 'abajo',
  download: 'descargar',
  draft: 'borrador',
  drafting: 'dibujo técnico',
  drama: 'teatro',
  drill: 'taladro',
  drive: 'unidad|disco',
  drizzle: 'llovizna',
  drone: 'dron',
  droplet: 'gota',
  droplets: 'gotas',
  drum: 'tambor',
  drumstick: 'muslo de pollo|baqueta',
  dumbbell: 'mancuerna|pesa',
  ear: 'oreja|oído',
  earth: 'tierra|planeta',
  egg: 'huevo',
  eject: 'expulsar',
  electric: 'eléctrico',
  ellipse: 'elipse',
  ellipsis: 'puntos suspensivos',
  end: 'fin|final',
  engine: 'motor',
  enter: 'entrar|intro',
  equal: 'igual',
  eraser: 'goma de borrar|borrador',
  ev: 'coche eléctrico|eléctrico',
  exclamation: 'exclamación',
  exclude: 'excluir',
  exit: 'salir|salida',
  expand: 'expandir|ampliar',
  expressionless: 'inexpresivo',
  external: 'externo',
  extinguisher: 'extintor',
  eye: 'ojo|ver',
  face: 'cara',
  factory: 'fábrica',
  fading: 'desvaneciendo',
  fan: 'ventilador|abanico',
  fast: 'rápido',
  faucet: 'grifo',
  feather: 'pluma',
  fence: 'valla|cerca',
  ferris: 'noria',
  file: 'archivo|fichero',
  files: 'archivos|ficheros',
  film: 'película',
  filter: 'filtro|filtrar',
  fingerprint: 'huella dactilar',
  fire: 'fuego|incendio',
  first: 'primero',
  fish: 'pez|pescado',
  fishing: 'pesca',
  fist: 'puño',
  fixed: 'fijo',
  flag: 'bandera',
  flame: 'llama|fuego',
  flashlight: 'linterna',
  flask: 'matraz',
  flexed: 'flexionado',
  floor: 'suelo|planta',
  flower: 'flor',
  focus: 'enfoque|enfocar',
  fog: 'niebla',
  fold: 'plegar|doblar',
  folder: 'carpeta',
  folders: 'carpetas',
  footprints: 'huellas|pisadas',
  fork: 'tenedor|bifurcación',
  forklift: 'carretilla elevadora',
  form: 'formulario',
  formatting: 'formato',
  forward: 'adelante|reenviar',
  forwarded: 'reenviado',
  fracture: 'fractura',
  frame: 'marco',
  franc: 'franco',
  freeform: 'forma libre',
  fried: 'frito',
  from: 'desde',
  front: 'frente|delante',
  frowning: 'ceño fruncido|triste',
  fuel: 'combustible|gasolina',
  full: 'lleno|completo',
  fullscreen: 'pantalla completa',
  function: 'función',
  funnel: 'embudo',
  galaxy: 'galaxia',
  gallery: 'galería',
  gamepad: 'mando|videojuego',
  gap: 'hueco|espacio',
  gauge: 'indicador|medidor',
  gavel: 'mazo|martillo de juez',
  gem: 'gema|joya',
  gemini: 'géminis',
  georgian: 'georgiano',
  germ: 'germen|microbio',
  ghost: 'fantasma',
  gift: 'regalo',
  glass: 'vaso|cristal',
  glasses: 'gafas',
  globe: 'globo terráqueo|mundo',
  goal: 'objetivo|meta',
  goggles: 'gafas protectoras',
  gpu: 'tarjeta gráfica',
  grab: 'agarrar',
  graduation: 'graduación',
  grape: 'uva',
  graph: 'gráfico',
  green: 'verde',
  grid: 'cuadrícula|rejilla',
  grinning: 'sonriente',
  grip: 'agarre|asa',
  group: 'grupo',
  guitar: 'guitarra',
  hail: 'granizo',
  half: 'mitad|medio',
  ham: 'jamón',
  hamburger: 'hamburguesa',
  hammer: 'martillo',
  hand: 'mano',
  handbag: 'bolso',
  handshake: 'apretón de manos|acuerdo',
  hard: 'duro',
  hash: 'almohadilla',
  hat: 'sombrero',
  haze: 'calima|neblina',
  hd: 'alta definición',
  head: 'cabeza',
  heading: 'encabezado|título',
  headphone: 'auricular',
  headphones: 'auriculares',
  headset: 'cascos|auriculares',
  heart: 'corazón',
  heater: 'calefactor|estufa',
  helicopter: 'helicóptero',
  helping: 'ayuda|ayudar',
  hexagon: 'hexágono',
  high: 'alto',
  highlighter: 'rotulador|subrayador',
  hook: 'gancho',
  hop: 'lúpulo|salto',
  hourglass: 'reloj de arena',
  house: 'casa|hogar',
  houses: 'casas',
  ice: 'hielo',
  id: 'identificación|carné',
  image: 'imagen|foto',
  images: 'imágenes|fotos',
  import: 'importar',
  in: 'dentro|entrada',
  inbox: 'bandeja de entrada',
  incoming: 'entrante',
  increase: 'aumentar',
  increasing: 'creciente',
  indent: 'sangría',
  indian: 'indio',
  infinity: 'infinito',
  info: 'información',
  initial: 'inicial',
  input: 'entrada',
  inside: 'dentro|interior',
  inspection: 'inspección',
  intersect: 'intersección',
  italic: 'cursiva',
  iteration: 'iteración',
  iv: 'gotero|vía intravenosa',
  japanese: 'japonés',
  justify: 'justificar',
  key: 'llave|clave',
  keyboard: 'teclado',
  keyhole: 'cerradura|ojo de cerradura',
  kindling: 'leña',
  king: 'rey',
  knife: 'cuchillo',
  knight: 'caballo|caballero',
  ladder: 'escalera de mano',
  lamp: 'lámpara',
  land: 'tierra|aterrizar',
  landing: 'aterrizaje',
  landmark: 'monumento|punto de referencia',
  languages: 'idiomas',
  lanyard: 'acreditación|cinta',
  laptop: 'portátil',
  large: 'grande',
  lasso: 'lazo',
  last: 'último',
  layer: 'capa',
  layers: 'capas',
  layout: 'diseño|disposición',
  leaf: 'hoja',
  leafy: 'frondoso|verdura',
  lectern: 'atril',
  left: 'izquierda',
  lens: 'lente|lupa',
  library: 'biblioteca',
  life: 'vida',
  ligature: 'ligadura',
  lightbulb: 'bombilla|idea',
  lighthouse: 'faro',
  lightning: 'rayo',
  line: 'línea',
  lines: 'líneas',
  link: 'enlace|vínculo',
  list: 'lista',
  loader: 'cargando',
  locate: 'localizar|ubicar',
  lock: 'candado|bloquear',
  locked: 'bloqueado',
  log: 'registro',
  logs: 'registros',
  lollipop: 'piruleta',
  lotion: 'loción|crema',
  low: 'bajo',
  lower: 'bajar|minúsculas',
  luggage: 'equipaje|maleta',
  machine: 'máquina',
  magnet: 'imán',
  mail: 'correo|email',
  mailbox: 'buzón',
  mails: 'correos',
  map: 'mapa',
  mark: 'marca',
  mars: 'marte',
  martini: 'cóctel',
  mask: 'máscara|mascarilla',
  maximize: 'maximizar',
  medal: 'medalla',
  medical: 'médico',
  medium: 'medio|mediano',
  megaphone: 'megáfono',
  memory: 'memoria',
  menu: 'menú',
  merge: 'fusionar|unir',
  message: 'mensaje',
  messages: 'mensajes',
  meter: 'medidor|contador',
  metronome: 'metrónomo',
  mic: 'micrófono',
  microchip: 'chip',
  microscope: 'microscopio',
  microwave: 'microondas',
  milestone: 'hito',
  milk: 'leche',
  minimal: 'mínimo',
  minimize: 'minimizar',
  minus: 'menos|restar',
  mirror: 'espejo',
  missed: 'perdida',
  monitor: 'pantalla',
  moon: 'luna',
  mop: 'fregona',
  more: 'más',
  mosque: 'mezquita',
  motorbike: 'moto|motocicleta',
  mountain: 'montaña',
  mouse: 'ratón',
  mouth: 'boca',
  move: 'mover',
  music: 'música',
  narrow: 'estrecho',
  navigation: 'navegación',
  nepali: 'nepalí',
  network: 'red',
  newspaper: 'periódico',
  not: 'distinto',
  note: 'nota',
  notebook: 'cuaderno|libreta',
  notepad: 'bloc de notas',
  notes: 'notas',
  nut: 'tuerca|nuez',
  octagon: 'octágono',
  of: 'de',
  off: 'apagado|desactivado',
  open: 'abrir|abierto',
  ophiuchus: 'ofiuco',
  option: 'opción',
  orbit: 'órbita',
  ordered: 'ordenado|numerado',
  out: 'fuera|salida',
  outgoing: 'saliente',
  outline: 'contorno',
  output: 'salida',
  package: 'paquete',
  paint: 'pintura|pintar',
  paintbrush: 'pincel|brocha',
  palette: 'paleta',
  palm: 'palmera|palma',
  panels: 'paneles',
  paper: 'papel',
  paperclip: 'clip',
  parasol: 'sombrilla',
  parentheses: 'paréntesis',
  park: 'parque',
  parking: 'aparcamiento',
  party: 'fiesta',
  paste: 'pegar',
  pattern: 'patrón',
  pause: 'pausa',
  paw: 'pata|huella',
  pawn: 'peón',
  pc: 'ordenador',
  pen: 'bolígrafo|pluma',
  pencil: 'lápiz|editar',
  pentagon: 'pentágono',
  percent: 'porcentaje|por ciento',
  person: 'persona',
  philippine: 'filipino',
  phone: 'teléfono',
  pickaxe: 'pico',
  picture: 'imagen|foto',
  pie: 'tarta|gráfico circular|quesito',
  piggy: 'cerdito|hucha',
  pilcrow: 'calderón|párrafo',
  pile: 'montón|pila',
  pill: 'pastilla|píldora',
  pin: 'chincheta|fijar|alfiler',
  pine: 'pino',
  pinned: 'fijado',
  pinwheel: 'molinillo',
  pipette: 'pipeta|cuentagotas',
  pisces: 'piscis',
  plane: 'avión',
  plant: 'planta',
  platter: 'bandeja',
  play: 'reproducir|jugar',
  playing: 'jugando|reproduciendo',
  plot: 'gráfico|trazar',
  plug: 'enchufe',
  plus: 'más|añadir',
  pocket: 'bolsillo',
  podium: 'podio',
  point: 'punto',
  pointer: 'puntero',
  pole: 'poste|polo',
  polygon: 'polígono',
  popcorn: 'palomitas',
  popper: 'cañón de confeti',
  popsicle: 'polo|helado',
  port: 'puerto',
  pot: 'olla|maceta',
  pound: 'libra',
  power: 'encendido|energía|apagar',
  presentation: 'presentación',
  print: 'imprimir',
  printer: 'impresora',
  projector: 'proyector',
  properties: 'propiedades',
  proportions: 'proporciones',
  pull: 'tirar|extraer',
  pulse: 'pulso',
  puzzle: 'rompecabezas|puzle',
  pyramid: 'pirámide',
  queen: 'reina',
  question: 'pregunta|ayuda',
  quote: 'cita|comillas',
  rabbit: 'conejo',
  rack: 'estante',
  radiation: 'radiación',
  radical: 'raíz',
  radius: 'radio',
  rain: 'lluvia',
  rainbow: 'arcoíris',
  range: 'rango',
  rat: 'rata',
  ratio: 'proporción',
  reader: 'lector',
  receipt: 'recibo|ticket',
  receiver: 'receptor',
  rectangle: 'rectángulo',
  recycle: 'reciclar',
  redo: 'rehacer',
  refresh: 'actualizar|refrescar',
  refrigerator: 'nevera|frigorífico',
  regex: 'expresión regular',
  remove: 'quitar|eliminar',
  repeat: 'repetir',
  replace: 'reemplazar',
  reply: 'responder',
  request: 'solicitud|petición',
  reset: 'restablecer|reiniciar',
  restart: 'reiniciar',
  restore: 'restaurar',
  rewind: 'rebobinar',
  ribbon: 'cinta|lazo',
  right: 'derecha',
  ring: 'anillo|timbre',
  road: 'carretera',
  rocket: 'cohete',
  rocking: 'mecedora',
  rod: 'caña|varilla',
  roller: 'rodillo|patines',
  rook: 'torre',
  root: 'raíz',
  rose: 'rosa',
  rotate: 'rotar|girar',
  round: 'redondo',
  route: 'ruta',
  rows: 'filas',
  ruble: 'rublo',
  ruler: 'regla',
  rupee: 'rupia',
  russian: 'ruso',
  sagittarius: 'sagitario',
  sailboat: 'velero',
  salad: 'ensalada',
  sandwich: 'bocadillo|sándwich',
  satellite: 'satélite',
  saudi: 'saudí',
  save: 'guardar',
  scale: 'escala|balanza',
  scaling: 'escalado',
  scan: 'escanear',
  scatter: 'dispersión',
  school: 'escuela|colegio',
  scissors: 'tijeras|cortar',
  scooter: 'patinete',
  scorpio: 'escorpio',
  screen: 'pantalla',
  scroll: 'pergamino|desplazar',
  search: 'buscar|búsqueda',
  searching: 'buscando',
  section: 'sección',
  select: 'seleccionar',
  send: 'enviar',
  sensitive: 'sensible',
  separator: 'separador',
  server: 'servidor',
  settings: 'ajustes|configuración',
  shapes: 'formas',
  share: 'compartir',
  sheet: 'hoja',
  shell: 'concha|terminal',
  shelving: 'estantería',
  shield: 'escudo|seguridad',
  ship: 'barco',
  shirt: 'camisa|camiseta',
  shoe: 'zapato',
  shopping: 'compras',
  shovel: 'pala',
  shower: 'ducha',
  shredder: 'trituradora',
  shrimp: 'gamba|camarón',
  shrink: 'encoger|reducir',
  shrub: 'arbusto',
  shuffle: 'aleatorio|mezclar',
  sign: 'señal|signo|cartel',
  signal: 'señal|cobertura',
  signature: 'firma',
  signpost: 'poste indicador|señal',
  single: 'único|individual',
  siren: 'sirena',
  skip: 'saltar|omitir',
  skull: 'calavera',
  slash: 'barra',
  slice: 'porción|rebanada',
  sliders: 'controles deslizantes|ajustes',
  slightly: 'ligeramente',
  small: 'pequeño',
  smartphone: 'móvil|teléfono',
  smiling: 'sonriente',
  smoke: 'humo',
  snail: 'caracol',
  snow: 'nieve',
  snowflake: 'copo de nieve',
  soap: 'jabón',
  soda: 'refresco',
  solid: 'sólido',
  sort: 'ordenar',
  soup: 'sopa',
  space: 'espacio',
  spade: 'pica|pala',
  sparkle: 'destello|brillo',
  sparkles: 'destellos|brillos',
  speaker: 'altavoz',
  speech: 'habla|diálogo',
  spell: 'ortografía',
  spline: 'curva',
  split: 'dividir|separar',
  spool: 'carrete|bobina',
  sport: 'deporte',
  spotlight: 'foco',
  spray: 'aerosol',
  spreadsheet: 'hoja de cálculo',
  sprout: 'brote|planta',
  square: 'cuadrado',
  squares: 'cuadrados',
  squiggle: 'garabato',
  squircle: 'cuadrado redondeado',
  squirrel: 'ardilla',
  stack: 'pila|montón',
  stacked: 'apilado',
  stairwell: 'escalera',
  stamp: 'sello',
  standing: 'de pie',
  star: 'estrella|favorito',
  start: 'inicio|empezar',
  step: 'paso',
  sterling: 'esterlina',
  stethoscope: 'estetoscopio|fonendoscopio',
  stick: 'palo',
  sticker: 'pegatina',
  sticky: 'adhesivo',
  stone: 'piedra',
  stop: 'parar|detener',
  store: 'tienda',
  stretch: 'estirar',
  strikethrough: 'tachado',
  stroke: 'trazo',
  style: 'estilo',
  subscript: 'subíndice',
  subtract: 'restar',
  summary: 'resumen',
  sun: 'sol',
  sunrise: 'amanecer',
  sunset: 'atardecer|puesta de sol',
  superscript: 'superíndice',
  swatch: 'muestra',
  swiss: 'suizo',
  switch: 'interruptor|cambiar',
  sword: 'espada',
  swords: 'espadas',
  symbol: 'símbolo',
  symlink: 'enlace simbólico',
  sync: 'sincronizar',
  syringe: 'jeringa|vacuna',
  table: 'tabla|mesa',
  tablet: 'tableta',
  tablets: 'pastillas|tabletas',
  tabs: 'pestañas',
  tag: 'etiqueta',
  tags: 'etiquetas',
  takeoff: 'despegue',
  tally: 'recuento|marcas de conteo',
  tangent: 'tangente',
  tape: 'cinta',
  target: 'objetivo|diana',
  taurus: 'tauro',
  telescope: 'telescopio',
  template: 'plantilla',
  tent: 'tienda de campaña',
  test: 'prueba',
  text: 'texto',
  theater: 'teatro',
  thermometer: 'termómetro|temperatura',
  thumbnails: 'miniaturas',
  thumbs: 'pulgar|me gusta',
  tic: 'tres en raya',
  ticket: 'entrada|billete|tique',
  tickets: 'entradas|billetes',
  timeline: 'línea de tiempo|cronología',
  timer: 'temporizador',
  to: 'a|hacia',
  todo: 'tarea|pendiente',
  toggle: 'alternar|interruptor',
  toilet: 'váter|inodoro|baño',
  tool: 'herramienta',
  toolbox: 'caja de herramientas',
  toothbrush: 'cepillo de dientes',
  top: 'arriba|superior',
  torus: 'toro',
  touchpad: 'panel táctil',
  towel: 'toalla',
  tower: 'torre',
  toy: 'juguete',
  track: 'pista',
  traffic: 'tráfico',
  trailer: 'remolque',
  train: 'tren',
  tram: 'tranvía',
  transgender: 'transgénero',
  trash: 'basura|papelera',
  treble: 'agudos|clave de sol',
  tree: 'árbol',
  trees: 'árboles',
  trending: 'tendencia',
  triangle: 'triángulo',
  triangles: 'triángulos',
  trophy: 'trofeo',
  truck: 'camión',
  tube: 'tubo',
  tubes: 'tubos',
  tunnel: 'túnel',
  turkish: 'turco',
  turntable: 'tocadiscos',
  turtle: 'tortuga',
  tv: 'televisión|tele',
  type: 'tipo|escribir',
  umbrella: 'paraguas',
  underline: 'subrayado',
  undo: 'deshacer',
  unfold: 'desplegar',
  ungroup: 'desagrupar',
  unit: 'unidad',
  unite: 'unir',
  university: 'universidad',
  unlink: 'desvincular',
  unplug: 'desenchufar',
  up: 'arriba',
  upload: 'subir|cargar',
  upper: 'mayúsculas|superior',
  upscale: 'ampliar',
  user: 'usuario',
  users: 'usuarios',
  utensils: 'cubiertos',
  utility: 'utilidad',
  vacuum: 'aspiradora',
  van: 'furgoneta',
  vault: 'caja fuerte',
  vegan: 'vegano',
  venetian: 'veneciana',
  vent: 'rejilla|ventilación',
  vibrate: 'vibrar',
  video: 'vídeo',
  videotape: 'cinta de vídeo',
  view: 'vista|ver',
  vocal: 'voz',
  voicemail: 'buzón de voz',
  volleyball: 'voleibol',
  volume: 'volumen',
  vote: 'votar|voto',
  wall: 'pared|muro',
  wallet: 'cartera',
  wallpaper: 'fondo de pantalla|papel pintado',
  wand: 'varita',
  warehouse: 'almacén',
  warning: 'aviso|advertencia',
  washing: 'lavadora|lavar',
  watch: 'reloj',
  water: 'agua',
  waveform: 'forma de onda',
  waves: 'olas|ondas',
  waypoints: 'puntos de ruta',
  webcam: 'cámara web',
  weight: 'peso',
  wheat: 'trigo',
  wheel: 'rueda',
  whistle: 'silbato',
  whole: 'entero',
  wide: 'ancho',
  wind: 'viento',
  window: 'ventana',
  wine: 'vino',
  word: 'palabra',
  workflow: 'flujo de trabajo',
  worm: 'gusano',
  wrap: 'ajustar|envolver',
  wrench: 'llave inglesa|herramienta',
  zap: 'rayo|electricidad',
  zero: 'cero',
  zodiac: 'zodiaco',
  zoom: 'ampliar|acercar',
  // ── Frequent words in icon tags ──
  academy: 'academia',
  access: 'acceso',
  accordion: 'acordeón',
  account: 'cuenta',
  accumulator: 'acumulador',
  achievement: 'logro',
  action: 'acción',
  active: 'activo',
  add: 'añadir|agregar|nuevo',
  added: 'añadido',
  adjust: 'ajustar',
  admin: 'administrador',
  aerial: 'aéreo',
  agile: 'ágil',
  agreement: 'acuerdo',
  ahead: 'adelante',
  ai: 'ia|inteligencia artificial',
  aid: 'ayuda|auxilio',
  aim: 'apuntar',
  airplane: 'avión',
  airwaves: 'ondas',
  albums: 'álbumes',
  alignment: 'alineación',
  allergy: 'alergia',
  alphabetical: 'alfabético',
  amenities: 'servicios',
  analytics: 'analítica',
  annotation: 'anotación',
  application: 'aplicación',
  arc: 'arco',
  architecture: 'arquitectura',
  armored: 'blindado',
  armoured: 'blindado',
  army: 'ejército',
  arrange: 'organizar|ordenar',
  art: 'arte',
  artist: 'artista',
  aspect: 'aspecto',
  assignment: 'asignación|tarea',
  assistant: 'asistente',
  astrology: 'astrología',
  astronomy: 'astronomía',
  attacked: 'atacado',
  attention: 'atención',
  audit: 'auditoría',
  audited: 'auditado',
  augmented: 'aumentada',
  authentication: 'autenticación',
  author: 'autor',
  authorization: 'autorización',
  authors: 'autores',
  auto: 'automático',
  automation: 'automatización',
  backwards: 'atrás|hacia atrás',
  bad: 'malo',
  baking: 'repostería|hornear',
  balance: 'equilibrio|saldo',
  band: 'banda|grupo',
  banking: 'banca',
  banned: 'prohibido',
  bars: 'barras',
  bathroom: 'baño|aseo',
  battle: 'batalla',
  bbq: 'barbacoa',
  beach: 'playa',
  bead: 'cuenta',
  beam: 'haz|rayo',
  behind: 'detrás',
  beverage: 'bebida',
  bidirectional: 'bidireccional',
  bill: 'factura|cuenta',
  billing: 'facturación',
  biology: 'biología',
  biometric: 'biométrico',
  biro: 'bolígrafo',
  birthdate: 'fecha de nacimiento',
  birthday: 'cumpleaños',
  blank: 'en blanco|vacío',
  bleed: 'sangrado',
  blind: 'ciego|persiana',
  block: 'bloque|bloquear',
  blocked: 'bloqueado',
  blood: 'sangre',
  blow: 'soplar',
  boat: 'barco|bote',
  booklet: 'folleto',
  books: 'libros',
  boolean: 'booleano',
  boost: 'impulsar',
  border: 'borde|frontera',
  boundary: 'límite',
  brainstorm: 'lluvia de ideas',
  bravery: 'valentía',
  breadth: 'anchura',
  break: 'descanso|romper',
  breakfast: 'desayuno',
  brewery: 'cervecería',
  bricks: 'ladrillos',
  brigade: 'brigada',
  bright: 'brillante',
  brightness: 'brillo',
  bristles: 'cerdas',
  british: 'británico',
  broadcast: 'emisión|difusión',
  bronze: 'bronce',
  browser: 'navegador',
  bubble: 'burbuja|bocadillo',
  build: 'construir|compilar',
  builder: 'constructor|albañil',
  bullet: 'viñeta|bala',
  busy: 'ocupado',
  button: 'botón',
  buy: 'comprar',
  cadet: 'cadete',
  calculate: 'calcular',
  camping: 'acampada',
  campsite: 'camping',
  cancel: 'cancelar',
  canceled: 'cancelado',
  cancellation: 'cancelación',
  cancelled: 'cancelado',
  capture: 'capturar',
  cardholder: 'titular de tarjeta',
  care: 'cuidado',
  caret: 'acento circunflejo',
  carousel: 'carrusel',
  cash: 'efectivo|dinero',
  caution: 'precaución',
  celebration: 'celebración|fiesta',
  celestial: 'celeste',
  cell: 'celda|célula',
  cellphone: 'móvil',
  celsius: 'grados',
  cement: 'cemento',
  centimeters: 'centímetros',
  certified: 'certificado',
  chain: 'cadena',
  change: 'cambio|cambiar',
  channels: 'canales',
  characters: 'caracteres',
  charge: 'carga|cargar',
  chassis: 'chasis',
  chat: 'charla|conversación',
  checked: 'comprobado',
  checkout: 'pagar|caja',
  chemistry: 'química',
  childhood: 'infancia',
  chop: 'picar|trocear',
  chord: 'acorde',
  chores: 'tareas domésticas',
  cinema: 'cine',
  clean: 'limpiar|limpio',
  clear: 'borrar|limpiar',
  clockwise: 'sentido horario',
  clone: 'clonar',
  cluster: 'grupo|clúster',
  coding: 'programación|código',
  coin: 'moneda',
  cold: 'frío',
  collectible: 'coleccionable',
  collection: 'colección',
  college: 'universidad',
  colors: 'colores',
  colour: 'color',
  colours: 'colores',
  combat: 'combate',
  comment: 'comentario',
  commerce: 'comercio',
  communication: 'comunicación',
  community: 'comunidad',
  comparison: 'comparación',
  compilation: 'recopilatorio',
  complete: 'completo|completar',
  completed: 'completado',
  compose: 'redactar',
  compromised: 'comprometido',
  computing: 'informática',
  concatenate: 'concatenar',
  conceal: 'ocultar',
  concert: 'concierto',
  configuration: 'configuración',
  confirm: 'confirmar',
  connect: 'conectar',
  connection: 'conexión',
  connections: 'conexiones',
  connectivity: 'conectividad',
  connector: 'conector',
  console: 'consola',
  constant: 'constante',
  constellation: 'constelación',
  consumer: 'consumidor',
  contactless: 'sin contacto',
  contacts: 'contactos',
  contagion: 'contagio',
  content: 'contenido',
  contract: 'contrato',
  controller: 'mando|controlador',
  controls: 'controles',
  conversation: 'conversación',
  coordinates: 'coordenadas',
  copies: 'copias',
  cores: 'núcleos',
  count: 'contar|recuento',
  counterfoil: 'matriz|resguardo',
  course: 'curso',
  cover: 'portada|cubierta',
  crafts: 'manualidades',
  crest: 'escudo|emblema',
  crime: 'delito|crimen',
  cruise: 'crucero',
  cube: 'cubo',
  cubes: 'cubos',
  curly: 'rizado',
  current: 'actual|corriente',
  curve: 'curva',
  cut: 'cortar',
  cybersecurity: 'ciberseguridad',
  cycle: 'ciclo',
  dairy: 'lácteos',
  damaged: 'dañado',
  damp: 'húmedo',
  danger: 'peligro',
  dark: 'oscuro',
  data: 'datos',
  date: 'fecha',
  day: 'día',
  deadline: 'fecha límite|plazo',
  deal: 'trato|oferta',
  debit: 'débito',
  debris: 'escombros',
  debug: 'depurar',
  deck: 'baraja',
  decor: 'decoración',
  decoration: 'decoración',
  defence: 'defensa',
  defenceless: 'indefenso',
  defender: 'defensor',
  defense: 'defensa',
  defenseless: 'indefenso',
  definition: 'definición',
  delivered: 'entregado',
  delivery: 'entrega|reparto',
  denied: 'denegado',
  department: 'departamento',
  depth: 'profundidad',
  description: 'descripción',
  deselect: 'deseleccionar',
  design: 'diseño',
  desktop: 'escritorio',
  details: 'detalles',
  detected: 'detectado',
  detection: 'detección',
  device: 'dispositivo',
  diagram: 'diagrama',
  dialog: 'diálogo',
  dialogue: 'diálogo',
  diary: 'diario',
  dictionary: 'diccionario',
  diet: 'dieta',
  digits: 'dígitos',
  dinner: 'cena',
  direction: 'dirección',
  directory: 'directorio|carpeta',
  disable: 'desactivar',
  disabled: 'desactivado|discapacidad',
  discard: 'descartar',
  disclosure: 'divulgación|desplegable',
  disconnect: 'desconectar',
  disconnected: 'desconectado',
  discount: 'descuento',
  discover: 'descubrir',
  disease: 'enfermedad',
  disinfect: 'desinfectar',
  disk: 'disco',
  dislike: 'no me gusta',
  display: 'pantalla|mostrar',
  distance: 'distancia',
  divider: 'divisor',
  division: 'división',
  diy: 'bricolaje',
  doctor: 'médico',
  document: 'documento',
  documentation: 'documentación',
  documents: 'documentos',
  done: 'hecho|terminado',
  dots: 'puntos',
  downgrade: 'bajar de versión',
  drag: 'arrastrar',
  draw: 'dibujar',
  drawer: 'cajón',
  drawers: 'cajones',
  drawing: 'dibujo',
  drink: 'bebida|beber',
  drop: 'gota|soltar',
  drug: 'fármaco|droga',
  duplicate: 'duplicar',
  dust: 'polvo',
  east: 'este',
  ecommerce: 'comercio electrónico',
  edit: 'editar',
  education: 'educación',
  egress: 'salida',
  electricity: 'electricidad',
  electronics: 'electrónica',
  element: 'elemento',
  eliminated: 'eliminado',
  email: 'correo',
  emergency: 'emergencia|urgencia',
  emotion: 'emoción',
  empty: 'vacío',
  encryption: 'cifrado',
  energy: 'energía',
  enlarge: 'agrandar|ampliar',
  enterprise: 'empresa',
  entertainment: 'entretenimiento',
  entrance: 'entrada',
  entries: 'entradas',
  entry: 'entrada',
  enumerate: 'enumerar',
  environment: 'entorno|medio ambiente',
  epidemic: 'epidemia',
  equaliser: 'ecualizador',
  equilateral: 'equilátero',
  equipment: 'equipo',
  erase: 'borrar',
  error: 'fallo',
  estimate: 'estimar|presupuesto',
  even: 'par',
  event: 'evento',
  events: 'eventos',
  excel: 'hoja de cálculo',
  exchange: 'cambio|intercambio',
  executable: 'ejecutable',
  exercise: 'ejercicio',
  experiment: 'experimento',
  expired: 'caducado',
  exploit: 'vulnerar',
  explore: 'explorar',
  export: 'exportar',
  extent: 'extensión',
  fahrenheit: 'grados',
  failed: 'fallido',
  failure: 'fallo',
  falling: 'bajada|caída',
  family: 'familia',
  favorite: 'favorito',
  favourite: 'favorito',
  feedback: 'opinión|comentarios',
  feet: 'pies',
  felt: 'fieltro',
  fewer: 'menos',
  fiction: 'ficción',
  field: 'campo',
  finance: 'finanzas',
  financial: 'financiero',
  find: 'encontrar|buscar',
  finished: 'terminado',
  firefighter: 'bombero',
  fireman: 'bombero',
  fitness: 'forma física|gimnasio',
  fix: 'arreglar',
  flash: 'destello',
  flex: 'flexible',
  float: 'flotante',
  floppy: 'disquete',
  flow: 'flujo',
  fluid: 'fluido',
  foam: 'espuma',
  font: 'fuente|letra',
  food: 'comida|alimento',
  foot: 'pie',
  forbidden: 'prohibido',
  forest: 'bosque',
  format: 'formato',
  formula: 'fórmula',
  found: 'encontrado',
  free: 'gratis|libre',
  freeze: 'congelar',
  freight: 'mercancías|flete',
  frequency: 'frecuencia',
  fresh: 'fresco',
  frozen: 'congelado',
  fruit: 'fruta',
  funds: 'fondos',
  furniture: 'muebles',
  further: 'más allá',
  gambling: 'apuestas',
  game: 'juego',
  gaming: 'videojuegos',
  garden: 'jardín',
  gate: 'puerta|verja',
  gateway: 'pasarela',
  gbp: 'libra esterlina',
  gear: 'engranaje',
  gelato: 'helado',
  gender: 'género',
  geometry: 'geometría',
  gizmo: 'artilugio',
  globule: 'glóbulo',
  gold: 'oro',
  good: 'bueno',
  graphics: 'gráficos',
  greater: 'mayor',
  greek: 'griego',
  grocery: 'supermercado|comestibles',
  guard: 'guardia',
  guardian: 'guardián',
  guide: 'guía',
  handle: 'asa|manija',
  happy: 'feliz|contento',
  harbor: 'puerto',
  harvest: 'cosecha',
  haulage: 'transporte',
  health: 'salud',
  healthcare: 'sanidad|asistencia sanitaria',
  healthy: 'saludable',
  hearing: 'oído|audición',
  heavy: 'pesado',
  height: 'altura',
  help: 'ayuda',
  hertz: 'hercio',
  hidden: 'oculto',
  hide: 'ocultar',
  hierarchy: 'jerarquía',
  history: 'historial|historia',
  hit: 'golpe',
  holiday: 'vacaciones|festivo',
  home: 'inicio|casa|hogar',
  homework: 'deberes',
  hopper: 'tolva',
  horoscope: 'horóscopo',
  hot: 'caliente',
  household: 'hogar|doméstico',
  housekeeping: 'limpieza',
  hr: 'recursos humanos',
  hygiene: 'higiene',
  icing: 'glaseado',
  identity: 'identidad',
  inactive: 'inactivo',
  inches: 'pulgadas',
  incorrect: 'incorrecto',
  increment: 'incrementar',
  index: 'índice',
  indicator: 'indicador',
  infantry: 'infantería',
  infected: 'infectado',
  infection: 'infección',
  information: 'información',
  informed: 'informado',
  ingress: 'entrada',
  injured: 'herido',
  ink: 'tinta',
  insect: 'insecto',
  insecure: 'inseguro',
  insert: 'insertar',
  instrument: 'instrumento',
  integration: 'integración',
  intellect: 'intelecto',
  intelligence: 'inteligencia',
  intentions: 'intenciones',
  intercepted: 'interceptado',
  interception: 'interceptación',
  interface: 'interfaz',
  intolerance: 'intolerancia',
  invincibility: 'invencibilidad',
  invincible: 'invencible',
  issue: 'incidencia|problema',
  issues: 'incidencias',
  items: 'elementos',
  janitor: 'conserje',
  join: 'unir|unirse',
  journal: 'diario',
  journey: 'viaje|trayecto',
  junk: 'basura',
  justice: 'justicia',
  keys: 'llaves|teclas',
  kitchen: 'cocina',
  knots: 'nudos',
  knowledge: 'conocimiento',
  knowledgeable: 'experto',
  lab: 'laboratorio',
  label: 'etiqueta',
  labourer: 'obrero',
  lactose: 'lactosa',
  landscape: 'paisaje|horizontal',
  language: 'idioma|lenguaje',
  law: 'ley',
  leaderboard: 'clasificación',
  leaflet: 'folleto',
  leak: 'fuga|filtración',
  learning: 'aprendizaje',
  leisure: 'ocio',
  length: 'longitud',
  less: 'menos',
  lesson: 'lección',
  letter: 'letra|carta',
  letters: 'letras',
  level: 'nivel',
  levels: 'niveles',
  licence: 'licencia',
  license: 'licencia',
  lift: 'ascensor|levantar',
  light: 'luz|claro',
  lighting: 'iluminación',
  like: 'me gusta',
  liner: 'transatlántico',
  linter: 'analizador',
  liquid: 'líquido',
  listen: 'escuchar',
  listing: 'listado',
  lit: 'encendido',
  live: 'en directo|vivo',
  living: 'salón|vida',
  loading: 'cargando|carga',
  location: 'ubicación|lugar',
  login: 'iniciar sesión|acceso',
  logistics: 'logística',
  logo: 'logotipo',
  loop: 'bucle',
  lorry: 'camión',
  loss: 'pérdida',
  lost: 'perdido',
  lot: 'lote',
  love: 'amor',
  lunch: 'almuerzo|comida',
  machinery: 'maquinaria',
  magazine: 'revista',
  magic: 'magia',
  magnifier: 'lupa',
  magnifying: 'lupa',
  maintenance: 'mantenimiento',
  major: 'mayor',
  malware: 'software malicioso',
  manage: 'gestionar',
  margin: 'margen',
  marine: 'marino',
  maritime: 'marítimo',
  marked: 'marcado',
  marker: 'marcador|rotulador',
  marketing: 'publicidad',
  markup: 'marcado',
  marquee: 'marquesina',
  materials: 'materiales',
  math: 'matemáticas',
  maximum: 'máximo',
  meal: 'comida',
  measure: 'medir|medida',
  measurements: 'medidas',
  meat: 'carne',
  mechanical: 'mecánico',
  media: 'multimedia',
  medication: 'medicación',
  medicine: 'medicina|medicamento',
  memo: 'nota',
  metre: 'metro',
  microbe: 'microbio',
  microorganism: 'microorganismo',
  microphone: 'micrófono',
  middle: 'medio|centro',
  mile: 'milla',
  military: 'militar',
  millimeters: 'milímetros',
  mind: 'mente',
  minimum: 'mínimo',
  mistake: 'error',
  mobile: 'móvil',
  moderate: 'moderado',
  module: 'módulo',
  moisture: 'humedad',
  monetization: 'monetización',
  money: 'dinero',
  monitoring: 'monitorización',
  month: 'mes',
  morning: 'mañana',
  mortar: 'mortero',
  motion: 'movimiento',
  movement: 'movimiento',
  movie: 'película',
  multiple: 'múltiple|varios',
  multiplication: 'multiplicación',
  multiply: 'multiplicar',
  multitask: 'multitarea',
  museum: 'museo',
  mute: 'silenciar|silencio',
  nature: 'naturaleza',
  nautical: 'náutico',
  navy: 'armada',
  networking: 'redes',
  new: 'nuevo',
  newsletter: 'boletín',
  next: 'siguiente',
  night: 'noche',
  node: 'nodo',
  noise: 'ruido',
  nomadic: 'nómada',
  north: 'norte',
  nothing: 'nada',
  notice: 'aviso',
  notification: 'notificación|aviso',
  novel: 'novela',
  novels: 'novelas',
  null: 'nulo',
  number: 'número',
  numerical: 'numérico',
  nutrition: 'nutrición',
  object: 'objeto',
  ocean: 'océano|mar',
  octave: 'octava',
  offense: 'ofensa',
  offer: 'oferta',
  office: 'oficina',
  offline: 'sin conexión',
  on: 'encendido',
  online: 'en línea',
  opened: 'abierto',
  operator: 'operador',
  optical: 'óptico',
  optics: 'óptica',
  options: 'opciones',
  or: 'o',
  oral: 'bucal',
  order: 'orden|pedido',
  organisation: 'organización',
  organiser: 'organizador',
  organization: 'organización',
  organizer: 'organizador',
  orientation: 'orientación',
  outbreak: 'brote',
  outdoors: 'aire libre',
  outlet: 'enchufe|toma',
  outwards: 'hacia fuera',
  over: 'sobre|encima',
  overflow: 'desbordamiento',
  overlap: 'superponer',
  overview: 'resumen|vista general',
  packages: 'paquetes',
  packaging: 'embalaje',
  padding: 'relleno',
  page: 'página',
  pages: 'páginas',
  pagination: 'paginación',
  pamphlet: 'panfleto|folleto',
  pandemic: 'pandemia',
  paperwork: 'papeleo',
  paragraph: 'párrafo',
  paragraphs: 'párrafos',
  parallel: 'paralelo',
  paraph: 'rúbrica',
  parcel: 'paquete',
  partly: 'parcialmente',
  parts: 'piezas',
  pass: 'pase|aprobar',
  passed: 'aprobado',
  password: 'contraseña',
  patch: 'parche',
  path: 'ruta|camino',
  pathfinder: 'explorador',
  pathogen: 'patógeno',
  payment: 'pago',
  pending: 'pendiente',
  people: 'personas|gente',
  performance: 'rendimiento',
  period: 'periodo|punto',
  permissions: 'permisos',
  pest: 'plaga',
  pet: 'mascota',
  photo: 'foto|fotografía',
  physics: 'física',
  pictures: 'imágenes|fotos',
  piece: 'pieza',
  pitch: 'tono',
  place: 'lugar',
  plain: 'simple',
  plan: 'planificar',
  planet: 'planeta',
  planner: 'agenda|planificador',
  planning: 'planificación',
  platinum: 'platino',
  playback: 'reproducción',
  playlist: 'lista de reproducción',
  podcast: 'pódcast',
  points: 'puntos',
  poker: 'póquer',
  police: 'policía',
  portable: 'portátil',
  portfolio: 'portafolio|cartera',
  positive: 'positivo',
  post: 'publicar|publicación',
  precision: 'precisión',
  preferences: 'preferencias',
  prescription: 'receta',
  pressure: 'presión',
  prevention: 'prevención',
  preview: 'vista previa',
  previous: 'anterior',
  price: 'precio',
  primary: 'principal|primario',
  prison: 'cárcel|prisión',
  pristine: 'impecable',
  privacy: 'privacidad',
  private: 'privado',
  prize: 'premio',
  processing: 'procesando',
  processor: 'procesador',
  produce: 'productos frescos',
  product: 'producto',
  productivity: 'productividad',
  products: 'productos',
  profile: 'perfil',
  programming: 'programación',
  progress: 'progreso',
  prohibited: 'prohibido',
  project: 'proyecto',
  projects: 'proyectos',
  prompt: 'consola|indicación',
  property: 'propiedad|inmueble',
  prose: 'prosa',
  protected: 'protegido',
  protection: 'protección',
  public: 'público',
  published: 'publicado',
  purchase: 'compra',
  push: 'empujar|enviar',
  quantity: 'cantidad',
  quarantine: 'cuarentena',
  queue: 'cola',
  quick: 'rápido',
  quotation: 'cita|presupuesto',
  railway: 'ferrocarril',
  rainfall: 'precipitación|lluvia',
  ram: 'memoria ram',
  random: 'aleatorio|azar',
  ranking: 'clasificación',
  rate: 'tasa|valorar',
  rating: 'valoración|puntuación',
  reaction: 'reacción',
  read: 'leer',
  reading: 'lectura',
  reality: 'realidad',
  reboot: 'reiniciar',
  recognition: 'reconocimiento',
  reconnect: 'reconectar',
  record: 'grabar|registro',
  recording: 'grabación|grabar',
  records: 'registros|discos',
  rectangles: 'rectángulos',
  reduce: 'reducir',
  reel: 'carrete|bobina',
  reflect: 'reflejar',
  reflow: 'reajustar',
  rejected: 'rechazado',
  relax: 'relajarse',
  reload: 'recargar',
  reminder: 'recordatorio',
  remote: 'remoto|mando',
  reorder: 'reordenar',
  repair: 'reparar',
  replay: 'repetir',
  repo: 'repositorio',
  report: 'informe',
  repository: 'repositorio',
  rerun: 'repetir',
  rescue: 'rescate',
  research: 'investigación',
  residence: 'residencia|vivienda',
  resize: 'redimensionar',
  resolution: 'resolución',
  response: 'respuesta',
  responsive: 'adaptable',
  rest: 'descanso',
  restaurant: 'restaurante',
  restricted: 'restringido',
  retail: 'comercio|tienda',
  reticule: 'retícula',
  reveal: 'revelar|mostrar',
  revealed: 'revelado',
  reverse: 'invertir|revés',
  review: 'reseña|revisión',
  revision: 'revisión',
  rising: 'subida|ascenso',
  roadmap: 'hoja de ruta',
  rock: 'roca',
  rodent: 'roedor',
  room: 'habitación|sala',
  rosette: 'escarapela',
  row: 'fila',
  rpm: 'revoluciones',
  rubber: 'goma',
  rule: 'regla',
  run: 'ejecutar|correr',
  running: 'en marcha|correr',
  safety: 'seguridad',
  sailing: 'navegar|vela',
  sale: 'rebajas|venta',
  sanitation: 'saneamiento',
  saved: 'guardado',
  scanned: 'escaneado',
  scanning: 'escaneando',
  schedule: 'horario|programar',
  science: 'ciencia',
  scope: 'alcance|mira',
  score: 'puntuación',
  scout: 'explorador',
  screens: 'pantallas',
  script: 'guion',
  scrubbing: 'fregar',
  sea: 'mar',
  seafood: 'marisco',
  secondary: 'secundario',
  secret: 'secreto',
  secure: 'seguro',
  security: 'seguridad',
  see: 'ver',
  seed: 'semilla',
  selection: 'selección',
  sentence: 'frase|condena',
  separate: 'separar',
  series: 'serie',
  servers: 'servidores',
  service: 'servicio',
  sex: 'sexo',
  shade: 'sombra',
  shades: 'tonos|sombras',
  shape: 'forma',
  sharing: 'compartir',
  sharp: 'afilado|sostenido',
  sheets: 'hojas',
  shiny: 'brillante',
  shipping: 'envío',
  show: 'mostrar',
  showtime: 'función|sesión',
  sidebar: 'barra lateral',
  sight: 'vista|mira',
  silence: 'silencio',
  silent: 'silencio|silencioso',
  silver: 'plata',
  sine: 'seno',
  singer: 'cantante',
  size: 'tamaño',
  sketch: 'boceto',
  sketchbook: 'cuaderno de dibujo',
  sleep: 'dormir|sueño',
  sleeve: 'funda',
  slip: 'resguardo',
  slot: 'ranura',
  slow: 'lento',
  smart: 'inteligente',
  smile: 'sonrisa',
  smoking: 'fumar',
  snack: 'aperitivo|merienda',
  snippet: 'fragmento',
  socket: 'enchufe|conector',
  soldier: 'soldado',
  song: 'canción',
  songs: 'canciones',
  sound: 'sonido',
  source: 'fuente|origen',
  south: 'sur',
  soy: 'soja',
  specs: 'especificaciones',
  speed: 'velocidad',
  spin: 'girar',
  spinner: 'indicador de carga',
  spinning: 'girando',
  spiral: 'espiral',
  sports: 'deportes',
  spotless: 'impecable',
  spread: 'extender',
  spring: 'primavera|muelle',
  squeeze: 'apretar',
  ssd: 'disco sólido',
  stacking: 'apilar',
  staff: 'personal|pentagrama',
  stage: 'escenario|fase',
  station: 'estación',
  stationary: 'inmóvil',
  stationery: 'papelería',
  stations: 'estaciones',
  statistics: 'estadísticas',
  status: 'estado',
  sticks: 'palos',
  stopped: 'detenido',
  stops: 'paradas',
  stopwatch: 'cronómetro',
  storage: 'almacenamiento',
  stories: 'historias',
  story: 'historia|cuento',
  stream: 'transmisión|directo',
  strength: 'fuerza',
  strong: 'fuerte',
  structure: 'estructura',
  student: 'estudiante|alumno',
  study: 'estudio|estudiar',
  subhead: 'subtítulo',
  subscribe: 'suscribirse',
  subtitles: 'subtítulos',
  subway: 'metro',
  success: 'éxito',
  sugar: 'azúcar',
  suit: 'palo|traje',
  suitcase: 'maleta',
  summer: 'verano',
  support: 'soporte|ayuda',
  surface: 'superficie',
  surveillance: 'vigilancia',
  surveyor: 'topógrafo',
  sustainability: 'sostenibilidad',
  swap: 'intercambiar',
  sweep: 'barrer',
  sweeping: 'barrer',
  sweet: 'dulce',
  swipe: 'deslizar',
  symbolic: 'simbólico',
  synchronise: 'sincronizar',
  synchronize: 'sincronizar',
  synthesiser: 'sintetizador',
  synthesizer: 'sintetizador',
  system: 'sistema',
  tab: 'pestaña',
  tabletop: 'juego de mesa',
  talk: 'hablar|charla',
  tank: 'tanque|depósito',
  tanker: 'petrolero',
  task: 'tarea',
  tasks: 'tareas',
  team: 'equipo',
  technology: 'tecnología',
  television: 'televisión',
  temperature: 'temperatura',
  terms: 'condiciones',
  tested: 'probado',
  testing: 'pruebas',
  than: 'que',
  theatre: 'teatro',
  theme: 'tema',
  threat: 'amenaza',
  throbber: 'indicador de carga',
  thwarted: 'frustrado',
  tick: 'marca|visto',
  ticked: 'marcado',
  tidy: 'ordenar',
  till: 'caja registradora',
  time: 'tiempo|hora',
  times: 'por|multiplicar',
  tin: 'lata',
  tip: 'punta|consejo',
  toiletries: 'artículos de aseo',
  token: 'ficha',
  tome: 'tomo',
  toolbar: 'barra de herramientas',
  tools: 'herramientas',
  toothpaste: 'pasta de dientes',
  touchscreen: 'pantalla táctil',
  tough: 'resistente',
  tourism: 'turismo',
  tracking: 'seguimiento',
  trading: 'bolsa|comercio',
  transaction: 'transacción',
  transcribe: 'transcribir',
  transcription: 'transcripción',
  transfer: 'transferencia',
  transform: 'transformar',
  translate: 'traducir',
  transmission: 'transmisión',
  transport: 'transporte',
  transportation: 'transporte',
  travel: 'viaje|viajar',
  trigonometry: 'trigonometría',
  trip: 'viaje',
  trolley: 'carrito',
  trooper: 'soldado',
  troubleshoot: 'diagnosticar',
  turn: 'girar|giro',
  two: 'dos',
  typing: 'escribiendo',
  typography: 'tipografía',
  unarmored: 'sin blindaje',
  unarmoured: 'sin blindaje',
  unavailable: 'no disponible',
  uncertified: 'sin certificar',
  unchain: 'desencadenar',
  undamaged: 'intacto',
  undefended: 'indefenso',
  undelivered: 'no entregado',
  underground: 'subterráneo|metro',
  unfavorite: 'quitar de favoritos',
  unfollow: 'dejar de seguir',
  unguarded: 'desprotegido',
  units: 'unidades',
  unlike: 'no me gusta',
  unlock: 'desbloquear',
  unprevented: 'sin prevenir',
  unprotected: 'desprotegido',
  unread: 'no leído',
  unsafe: 'inseguro|peligroso',
  unsecured: 'no protegido',
  unshielded: 'sin protección',
  unsubscribe: 'darse de baja',
  unverified: 'sin verificar',
  upgrade: 'mejorar|actualizar',
  url: 'dirección web',
  usd: 'dólar',
  used: 'usado',
  vacation: 'vacaciones',
  valid: 'válido',
  vegetable: 'verdura|hortaliza',
  vegetarian: 'vegetariano',
  vehicle: 'vehículo',
  verification: 'verificación',
  verified: 'verificado',
  version: 'versión',
  versions: 'versiones',
  vessel: 'buque',
  vigilance: 'vigilancia',
  vigilant: 'vigilante',
  vineyard: 'viñedo',
  vinyl: 'vinilo',
  visibility: 'visibilidad',
  vision: 'visión',
  vitamin: 'vitamina',
  vm: 'máquina virtual',
  vocals: 'voces',
  voice: 'voz',
  void: 'vacío|anular',
  voucher: 'vale|cupón',
  vpn: 'red privada',
  vulnerability: 'vulnerabilidad',
  wait: 'esperar',
  war: 'guerra',
  warmth: 'calor',
  wash: 'lavar',
  waste: 'residuos|basura',
  wavelength: 'longitud de onda',
  way: 'camino',
  waypoint: 'punto de ruta',
  weakness: 'debilidad',
  weapon: 'arma',
  weather: 'tiempo|clima',
  webpage: 'página web',
  west: 'oeste',
  wet: 'mojado',
  widescreen: 'panorámico',
  width: 'anchura|ancho',
  wilderness: 'naturaleza salvaje',
  winery: 'bodega',
  winner: 'ganador',
  wireless: 'inalámbrico',
  wood: 'madera',
  work: 'trabajo',
  world: 'mundo',
  write: 'escribir',
  writer: 'escritor',
  writing: 'escritura|escribir',
  written: 'escrito',
  wrong: 'incorrecto',
  year: 'año',
  zip: 'comprimido',
};

/**
 * Words of icon names that need no translation: numbers and letters, words
 * spelled the same in Spanish (`radio`, `taxi`, `piano`), names, zodiac signs
 * and currencies that do not change, and technical terms used as-is
 * (`git`, `usb`, `wifi`).
 */
export const ICON_SEARCH_ES_UNTRANSLATED: readonly string[] = [
  '0',
  '1',
  '10',
  '11',
  '12',
  '2',
  '2x2',
  '3',
  '3d',
  '3x2',
  '3x3',
  '4',
  '5',
  '6',
  '7',
  '8',
  '9',
  'a',
  'airplay',
  'aries',
  'audio',
  'bitcoin',
  'bluetooth',
  'c',
  'cable',
  'control',
  'copyleft',
  'cursor',
  'diagonal',
  'eclipse',
  'ethernet',
  'euro',
  'gantt',
  'git',
  'hdmi',
  'horizontal',
  'hospital',
  'hotel',
  'joystick',
  'kanban',
  'kayak',
  'lambda',
  'lari',
  'leo',
  'libra',
  'lira',
  'm',
  'mac',
  'metal',
  'midi',
  'neutral',
  'nfc',
  'no',
  'non',
  'omega',
  'origami',
  'panda',
  'panel',
  'peso',
  'phi',
  'pi',
  'piano',
  'pizza',
  'qr',
  'radar',
  'radio',
  'rectangular',
  'riyal',
  'robot',
  'router',
  'rss',
  'sigma',
  'sim',
  'sofa',
  'solar',
  'tac',
  'taxi',
  'terminal',
  'tilde',
  'toe',
  'tornado',
  'tractor',
  'usb',
  'variable',
  'vector',
  'venus',
  'vertical',
  'virgo',
  'virus',
  'webhook',
  'wifi',
  'x',
  'xml',
  'yen',
  'z',
];
